services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: stellarnest
      POSTGRES_PASSWORD: stellarnest
      POSTGRES_DB: stellarnest
    ports:
      - '5432:5432'
    volumes:
      - stellarnest-postgres:/var/lib/postgresql/data

volumes:
  stellarnest-postgres:
